services:
  frontend:
    build: ./frontend
    image: ghcr.io/hasanaranna/goodreads-frontend:latest
    container_name: goodreads-frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    image: ghcr.io/hasanaranna/goodreads-backend:latest
    container_name: goodreads-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: goodreads-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=goodreads
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data:z

volumes:
  db_data: